### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by noodlebreak** [cooncesean/mixpanel-query-py#24]
Hi, I just tried out your package today.
I was going to do this:

    query_client.get_events_unique

But turned out, there *is* no get_events_unique in your client module. I can only find these:

	In [14]: qc.get_events
	qc.get_events      qc.get_events_top

**Comment by cooncesean** [comment]
Try using `qc.get_events(data_type=qc.DATA_TYPE_UNQIUE)`.

[Here is the "unique" data type](https://github.com/cooncesean/mixpanel-query-py/blob/master/mixpanel_query/client.py#L33)

[Here is the `get_events` method signature](https://github.com/cooncesean/mixpanel-query-py/blob/master/mixpanel_query/client.py#L163).

Let me know if this works for ya :)

**Comment by noodlebreak** [comment]
Yeah I actually figured it out once I took a look the client module that day.

Anyways, can you help me with a query I can't figure out how to achieve using your API?

What I want to do is, basically, get the total counts of $referrers between a time range.

Currently, doing this:

    api.get_segmentation('visit', '2016-04-30', '2016-05-01',
    limit=5, on='properties["$referrer"]', where='"noodlebreak" == properties["username"]')

Gives me this:

    {u'data': {u'series': [u'2016-04-30', u'2016-05-01'],
               u'values': {u'http://m.facebook.com': {u'2016-04-30': 96,
                                                      u'2016-05-01': 144},
                           u'http://m.facebook.com/': {u'2016-04-30': 112,
                                                       u'2016-05-01': 191},
                           u'https://www.google.co.in/': {u'2016-04-30': 178,
                                                          u'2016-05-01': 159},
                           u'undefined': {u'2016-04-30': 315,
                                          u'2016-05-01': 342}}},

But I want the total counts of all the days, instead of getting the values for each top referrer by date, within the specified start and end time.

I have looked over each method of the API, and I can't think of any that can do this.

**Comment by cooncesean** [comment]
@thesmallestduck do you know if Mixpanel's API supports this type of query?

**Comment by thesmallestduck** [comment]
Hi @noodlebreak . This library utilizes the published API endpoints you can find here: https://mixpanel.com/docs/api-documentation/data-export-api (and some un published ones as well). The sum roll-up you are requesting seems like more of a post-processing step to me? Is there a reason you can't map a `sum` operation across the date values in the segments your request to achieve the totals you're looking for?

**Comment by noodlebreak** [comment]
@thesmallestduck I am actually doing that in Python yes, but I just wanted to know if it was doable on Mixpanel itself. The closes thing I found was /events/properties/values endpoint, but it didn't have filtering with the where clause like the segmentation API.
