### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jaredmixpanel** [cooncesean/mixpanel-query-py#25]
Hi @cooncesean , Jared from Mixpanel Support here... I'm working on a tool myself for importing/exporting Mixpanel data and I really liked your ConcurrentPaginator class and was hoping to use it. In order for me to do so though, you'd have to include an open-source license with your GitHub repo. Is that something you're open to? Look forward to hearing from you!

**Comment by cooncesean** [comment]
I'm totally fine with that.

Just reply with whatever needs to be added to our current license.

**Comment by jaredmixpanel** [comment]
Awesome, I just noticed that you have it categorized with an MIT License on PyPI so I made a PR to add a license file to the repo. Thanks so much!

**Comment by frifri** [comment]
This has been addressed. closing.
