### ISSUE TITLE
Old authentication scheme now causes 400 responses for all API requests

### ISSUE THREAD

**Issue by robin900** [cooncesean/mixpanel-query-py#28]
As of 6:26pm New York time today.

https://mixpanel.com/help/reference/data-export-api#authentication

**Comment by jaredmixpanel** [comment]
@robin900 @cooncesean Jared from Mixpanel support here, really sorry about this disruption. Our old authentication scheme is definitely still supported. This was a temporary issue that only affected the /export raw data API. It has been fixed and everything should be back to normal now.

**Comment by robin900** [comment]
@jaredmixpanel Well, thanks for letting us know. Is there a planned date for removal of the old authentication?

**Comment by jaredmixpanel** [comment]
@robin900 No, at this time there are no plans of dropping support for the old authentication method.

**Comment by thesmallestduck** [comment]
@jaredmixpanel thanks for chiming in and giving us a heads up on the issue and mixpanel's deprecation plans. I'm not an expert, but the old method of authentication seems more secure, if more onerous of the uninitiated developer. Can you share any insight into the thinking behind the deprecation?

**Comment by cooncesean** [comment]
@jaredmixpanel did Mixpanel recently "flip the switch" and begin to deny access to the API for clients using the old authentication scheme. Our production stack is receiving a flood of 400 response codes from MixPanel starting at ~2:18pm PST today.

**Comment by jaredmixpanel** [comment]
@cooncesean No, and there are still no plans whatsoever to do so. If you need further assistance troubleshooting the issue please write into support@mixpanel.com

**Comment by cooncesean** [comment]
Closed by https://github.com/cooncesean/mixpanel-query-py/pull/30.

@jaredmixpanel apologies; this was the wrong medium for that type of question. That said, thx for the quick response and will send all future troubleshooting requests to support 👍
